#
# Makefile
#

CC              ?= gcc
CXX             ?= g++
LVGL_DIR_NAME   ?= lvgl
LVGL_DIR        ?= .

WARNINGS        := -Wall -Wshadow -Wundef -Wmissing-prototypes -Wno-discarded-qualifiers -Wextra -Wno-unused-function -Wno-error=strict-prototypes -Wpointer-arith \
                   -fno-strict-aliasing -Wno-error=cpp -Wuninitialized -Wmaybe-uninitialized -Wno-unused-parameter -Wno-missing-field-initializers -Wtype-limits \
                   -Wsizeof-pointer-memaccess -Wno-format-nonliteral -Wno-cast-qual -Wunreachable-code -Wno-switch-default -Wreturn-type -Wmultichar -Wformat-security \
                   -Wno-ignored-qualifiers -Wno-error=pedantic -Wno-sign-compare -Wno-error=missing-prototypes -Wdouble-promotion -Wclobbered -Wdeprecated -Wempty-body \
                   -Wshift-negative-value -Wstack-usage=2048 -Wno-unused-value -std=gnu99
CFLAGS          ?= -O3 -g0 -I$(LVGL_DIR)/ -I./src -I./ui -I./common $(WARNINGS)
LDFLAGS         ?= -lm -lpthread

BIN             = main
BUILD_DIR       = ./build
BUILD_OBJ_DIR   = $(BUILD_DIR)/obj
BUILD_BIN_DIR   = $(BUILD_DIR)/bin

prefix          ?= /usr
bindir          ?= $(prefix)/bin

# Collect source files recursively
CSRCS           := $(shell find src -type f -name '*.c')
CXXSRCS         := $(shell find src -type f -name '*.cpp')
# Include UI sources (generated by EEZ); actions.cpp is ours, các file UI khác có thể bị overwrite nhưng vẫn cần link
UI_CSRCS        := $(shell find ui -maxdepth 1 -type f -name '*.c')
UI_CXXSRCS      := $(shell find ui -maxdepth 1 -type f -name '*.cpp')
CSRCS           += $(UI_CSRCS)
CXXSRCS         += $(UI_CXXSRCS)
COMMON_CXXSRCS  := $(shell find common -maxdepth 1 -type f -name '*.cpp')
CXXSRCS         += $(COMMON_CXXSRCS)

# Tuỳ chọn: bật buzzer thật với wiringPi khi build trên ARM
# Ưu tiên tự phát hiện nếu wiringPi.h tồn tại
ifneq (,$(wildcard /usr/include/wiringPi.h))
 CFLAGS   += -DENABLE_WIRING_PI
 CXXFLAGS += -DENABLE_WIRING_PI
 LDFLAGS  += -lwiringPi
else ifneq (,$(wildcard /usr/local/include/wiringPi.h))
 CFLAGS   += -DENABLE_WIRING_PI
 CXXFLAGS += -DENABLE_WIRING_PI
 LDFLAGS  += -L/usr/local/lib -lwiringPi
else ifeq ($(WIRINGPI),1)
 # fallback: cho phép ép bật qua biến môi trường
 CFLAGS   += -DENABLE_WIRING_PI
 CXXFLAGS += -DENABLE_WIRING_PI
 LDFLAGS  += -lwiringPi
endif

# Include LVGL sources
include $(LVGL_DIR)/lvgl/lvgl.mk

OBJEXT          ?= .o

COBJS           = $(CSRCS:.c=$(OBJEXT))
CXXOBJS         = $(CXXSRCS:.cpp=$(OBJEXT))
AOBJS           = $(ASRCS:.S=$(OBJEXT))

SRCS            = $(ASRCS) $(CSRCS) $(CXXSRCS)
OBJS            = $(AOBJS) $(COBJS) $(CXXOBJS)
TARGET          = $(addprefix $(BUILD_OBJ_DIR)/, $(patsubst ./%, %, $(OBJS)))

all: default

$(BUILD_OBJ_DIR)/%.o: %.c lv_conf.h
	@mkdir -p $(dir $@)
	@$(CC)  $(CFLAGS) -c $< -o $@
	@echo "CC  $<"

$(BUILD_OBJ_DIR)/%.o: %.cpp lv_conf.h
	@mkdir -p $(dir $@)
	@$(CXX)  $(CFLAGS) -c $< -o $@
	@echo "CXX $<"

$(BUILD_OBJ_DIR)/%.o: %.S lv_conf.h
	@mkdir -p $(dir $@)
	@$(CC)  $(CFLAGS) -c $< -o $@
	@echo "AS  $<"

default: $(TARGET)
	@mkdir -p $(dir $(BUILD_BIN_DIR)/)
	$(CXX) -o $(BUILD_BIN_DIR)/$(BIN) $(TARGET) $(LDFLAGS)

clean:
	rm -rf $(BUILD_DIR)

install:
	install -d $(DESTDIR)$(bindir)
	install $(BUILD_BIN_DIR)/$(BIN) $(DESTDIR)$(bindir)

uninstall:
	$(RM) -r $(addprefix $(DESTDIR)$(bindir)/,$(BIN))

